### ISSUE TITLE
where can i get the file of gopro.pkl

### ISSUE THREAD

**Issue by verigle** [ZhijianJiang/DispNet-TensorFlow#1]
Traceback (most recent call last):
  File "D:/Users/acer/PycharmProjects/DispNet-TensorFlow/DispNet.py", line 419, in <module>
    main()
  File "D:/Users/acer/PycharmProjects/DispNet-TensorFlow/DispNet.py", line 318, in main
    with open(GT_DIR) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/gopro.pkl'

**Comment by ZhijianJiang** [comment]
Sorry for confusion.

This file is the train data. You should use [`pickle`](https://docs.python.org/3/library/pickle.html) to convert your pictures to this format.

Wish it will help.

**Comment by verigle** [comment]
thank you

**Comment by sunnyHelen** [comment]
Is the prepfm.py used to produce gopro2.pkl? so I want to ask what it is in this directory?
base1 = '/home/visg1/jzj/Data_fin2/gt
thank you for your sharing.
